### ISSUE TITLE
HeatMap

### ISSUE THREAD

**Issue by cjzhzh** [Zero-We/BCL#3]
Hi @Zero-We ：
 Could you please explain how the heat map in your article was implemented and if there are any code references available?

**Comment by zihou98** [comment]
Hi, we normalize the attention value of each patch and map them to the colorbar for creating MIL-classifier heatmap. For patch-classifier heatmap, we use scores of the patch classifier. I may release the code later, or you can refer to [CLAM](https://github.com/mahmoodlab/CLAM/blob/master/create_heatmaps.py)
