### ISSUE TITLE
参数设置

### ISSUE THREAD

**Issue by jasonyin20** [Zero-We/BCL#5]
你好，感谢你的开源，我想请教一个问题，你们使用clam提取特征时，第一步前景提取是使用哪个预设置参数的。

**Comment by zihou98** [comment]
你好，create_patch步骤，对于TCGA数据集大部分WSI采用默认参数即sthresh=8, mthresh=7, Camelyon数据集大部分采用sthresh=18, mthresh=7，进一步观察masks组织分割结果，适当调整部分slide的sthresh和a_t，a_h参数

**Comment by jasonyin20** [comment]
明白了，非常感谢。
